spring:
  application:
    name: eureka-server-dev
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  server:
    enable-self-preservation: false
cmiot:
  cat:
    enabled: true
---
spring:
  profiles: dev
server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://172.16.1.101:8080/eureka/,http://172.16.1.102:8080/eureka/,http://172.16.1.103:8080/eureka/
---
spring:
  profiles: test
server:
  port: 8062
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://172.16.1.105:8060/eureka/,http://172.16.1.106:8060/eureka/,http://172.16.1.107:8060/eureka/
---
spring:
  profiles: peer3
server:
  port: 8063
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://172.16.1.101:8080/eureka/,http://172.16.1.102:8080/eureka/,http://172.16.1.103:8080/eureka/
